# -- 网站配置 --
# 有关每个参数的更多详细信息，请参阅主题文档。
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # 取消注释此行以启用主题
baseURL = "http://h.shimoxi.qzz.io/" # 网站基础URL
defaultContentLanguage = "zh-cn" # 默认内容语言

# pluralizeListTitles = "true" # 适用于非英语语言的Hugo函数，更多详情请查看 https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true # 启用robots.txt文件
summaryLength = 0 # 摘要长度

buildDrafts = false # 是否构建草稿文章
buildFuture = false # 是否构建未来日期的文章

enableEmoji = true # 启用Emoji支持

# googleAnalytics = "G-XXXXXXXXX" # Google Analytics跟踪ID

[pagination]
  pagerSize = 100 # 分页大小

[imaging]
  anchor = 'Center' # 图像锚点位置
  quality = 85 # 图像质量
  resampleFilter = 'CatmullRom' # 重采样过滤器

[taxonomies]
  tag = "tags" # 标签分类
  category = "categories" # 分类
  author = "authors" # 作者分类
  series = "series" # 系列分类

[sitemap]
  changefreq = 'daily' # Sitemap更新频率
  filename = 'sitemap.xml' # Sitemap文件名
  priority = 0.5 # Sitemap优先级

[outputs]
  home = ["HTML", "RSS", "JSON"] # 首页输出格式

[related]
  threshold = 0 # 相关内容阈值
  toLower = false # 是否转换为小写

    [[related.indices]]
        name = "tags"
        weight = 100 # 标签权重

    [[related.indices]]
        name = "categories"
        weight = 100 # 分类权重

    [[related.indices]]
        name = "series"
        weight = 50 # 系列权重

    [[related.indices]]
        name = "authors"
        weight = 20 # 作者权重

    [[related.indices]]
        name = "date"
        weight = 10 # 日期权重

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10 # 片段引用权重
