# -- 语言配置 (中文) --
# 此文件配置中文语言相关设置

disabled = false # 是否禁用此语言
languageCode = "zh-cn" # 语言代码
languageName = "中文" # 语言显示名称
weight = 1 # 语言权重，用于排序
title = "博客" # 网站标题

[params]
  displayName = "中文" # 显示名称
  isoCode = "zh-cn" # ISO语言代码
  rtl = false # 是否从右到左的语言
  dateFormat = "2 January 2006" # 日期格式
  # logo = "img/logo.png" # 网站Logo
  # secondaryLogo = "img/secondary-logo.png" # 次要Logo
  # description = "My awesome website" # 网站描述
  # copyright = "Copy, _right?_ :thinking_face:" # 版权信息

  # 头像配置
  [params.author]
    image = "https://jihulab.com/shimoxijimu/img2/raw/main/pictures/2025/08/22_13_42_2_6894b49f58cb8da5c80fd8e5.webp" # 作者头像

  # -- 首页配置 --
  [params.homepage]
    showRecent = true # 是否显示最近文章
    showRecentItems = 10 # 显示最近文章的数量
    showMoreLink = true # 是否显示"更多"链接
    showMoreLinkDest = "/posts/" # "更多"链接目标页面
    cardView = true # 是否以卡片视图显示文章
    cardViewScreenWidth = true # 是否根据屏幕宽度调整卡片视图
    layoutBackgroundBlur = false # 是否启用背景模糊效果
    disableHeroImageFilter = false # 是否禁用首页图像滤镜

# 作者信息配置示例（已注释）
# [params.author]
#   name = "Your name here" # 作者姓名
#   email = "youremail@example.com" # 作者邮箱
#   image = "img/blowfish_logo.png" # 作者头像
#   imageQuality = 96 # 图像质量
#   headline = "I'm only human" # 作者标题
#   bio = "A little bit about you" # 作者简介
#   # 社交媒体链接配置
#   links = [
#     { email = "mailto:hello@your_domain.com" }, # 邮箱
#     { link = "https://link-to-some-website.com/" }, # 个人网站
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" }, # Amazon
#     { apple = "https://www.apple.com" }, # Apple
#     { blogger = "https://username.blogspot.com/" }, # Blogger
#     { bluesky = "https://bsky.app/profile/username" }, # Bluesky
#     { codepen = "https://codepen.io/username" }, # CodePen
#     { dev = "https://dev.to/username" }, # Dev.to
#     { discord = "https://discord.gg/invitecode" }, # Discord
#     { dribbble = "https://dribbble.com/username" }, # Dribbble
#     { facebook = "https://facebook.com/username" }, # Facebook
#     { flickr = "https://www.flickr.com/photos/username/" }, # Flickr
#     { foursquare = "https://foursquare.com/username" }, # Foursquare
#     { github = "https://github.com/username" }, # GitHub
#     { gitlab = "https://gitlab.com/username" }, # GitLab
#     { google = "https://www.google.com/" }, # Google
#     { hashnode = "https://username.hashnode.dev" }, # Hashnode
#     { instagram = "https://instagram.com/username" }, # Instagram
#     { itch-io = "https://username.itch.io" }, # Itch.io
#     { keybase = "https://keybase.io/username" }, # Keybase
#     { keyoxide = "https://keyoxide.org/URI" }, # Keyoxide
#     { kickstarter = "https://www.kickstarter.com/profile/username" }, # Kickstarter
#     { lastfm = "https://lastfm.com/user/username" }, # Last.fm
#     { linkedin = "https://linkedin.com/in/username" }, # LinkedIn
#     { mastodon = "https://mastodon.instance/@username" }, # Mastodon
#     { matrix = "https://matrix.to/#/URI" }, # Matrix
#     { medium = "https://medium.com/username" }, # Medium
#     { microsoft = "https://www.microsoft.com/" }, # Microsoft
#     { orcid = "https://orcid.org/userid" }, # ORCID
#     { patreon = "https://www.patreon.com/username" }, # Patreon
#     { pinterest = "https://pinterest.com/username" }, # Pinterest
#     { reddit = "https://reddit.com/user/username" }, # Reddit
#     { researchgate = "https://www.researchgate.net/profile/username" }, # ResearchGate
#     { signal = "https://signal.me/#eu/userid" }, # Signal
#     { slack = "https://workspace.url/team/userid" }, # Slack
#     { snapchat = "https://snapchat.com/add/username" }, # Snapchat
#     { soundcloud = "https://soundcloud.com/username" }, # SoundCloud
#     { spotify = "https://open.spotify.com/user/userid" }, # Spotify
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" }, # Stack Overflow
#     { steam = "https://steamcommunity.com/profiles/userid" }, # Steam
#     { telegram = "https://t.me/username" }, # Telegram
#     { threads = "https://www.threads.net/@username" }, # Threads
#     { tiktok = "https://tiktok.com/@username" }, # TikTok
#     { tumblr = "https://username.tumblr.com" }, # Tumblr
#     { twitch = "https://twitch.tv/username" }, # Twitch
#     { twitter = "https://twitter.com/username" }, # Twitter
#     { x-twitter = "https://twitter.com/username" }, # X (Twitter)
#     { whatsapp = "https://wa.me/phone-number" }, # WhatsApp
#     { youtube = "https://youtube.com/username" }, # YouTube
#     { ko-fi = "https://ko-fi.com/username" }, # Ko-fi
#     { codeberg = "https://codeberg.org/username"}, # Codeberg
#   ]