# -- 主菜单 --
# 主菜单显示在页面顶部的页眉中。
# 可接受的参数包括：name（名称）、pageRef（页面引用）、page（页面）、url（链接）、title（标题）、weight（权重）。
#
# 最简单的菜单配置是提供：
#   name = 此菜单链接显示的名称
#   pageRef = 要链接到的页面或部分的标识符
#
# 默认情况下，菜单按字母顺序排列。可以通过提供权重值来覆盖此设置。
# 菜单将按权重从低到高排序。

[[main]]
  name = "博客" # 菜单显示名称
  pageRef = "posts" # 链接到posts部分
  weight = 10 # 菜单权重，用于排序

[[main]]
  name = "分类" # 菜单显示名称
  pageRef = "categories" # 链接到categories部分
  weight = 20 # 菜单权重，用于排序

[[main]]
  name = "标签" # 菜单显示名称
  pageRef = "tags" # 链接到tags部分
  weight = 30 # 菜单权重，用于排序

# -- 页脚菜单 --
# 页脚菜单显示在页面底部，紧接在版权声明之前。
# 配置方式与主菜单相同。


[[footer]]
  name = "标签" # 页脚菜单显示名称
  pageRef = "tags" # 链接到tags部分
  weight = 10 # 菜单权重，用于排序

[[footer]]
  name = "分类" # 页脚菜单显示名称
  pageRef = "categories" # 链接到categories部分
  weight = 20 # 菜单权重，用于排序